[opening_hours]
# TODO: Remove seconds once `@std/toml` supports TOML v1.1.0
# See: <https://github.com/denoland/std/pull/6964>
monday.open = 09:00:00
monday.close = 17:00:00
tuesday.open = 09:00:00
tuesday.close = 17:00:00
wednesday.open = 09:00:00
wednesday.close = 17:00:00
thursday.open = 09:00:00
thursday.close = 17:00:00
friday.open = 09:00:00
friday.close = 17:00:00

[special]
title = "Mio Mio Mai"
image = "getraenke.webp"
image_alt = "Flaschen verschiedener Mate- und Colasorten auf einem Regal"
description = "Mehr Mate im Mai. Mio Mio Getränke gibt es diesen Monat für 1.30€!"
year_month = "2024-05"

# Events

[[events]]
date_time = 2024-05-07T18:30:00
title = "Spieleabend"
image = "spieleabend.webp"
image_alt = "Handkarten eines Spielers des Brettspiels „7 Wonders“"
summary = """
	Mit Brett, Karten, oder an der Leinwand. Wir treffen uns zum Essen, Quatschen,
	und natürlich Spielen. Kommt vorbei!"""

[[events]]
date_time = 2024-05-07T18:30:00
title = "Spieleabend"
image = "spieleabend.webp"
image_alt = "Handkarten eines Spielers des Brettspiels „7 Wonders“"
summary = """
	Mit Brett, Karten, oder an der Leinwand. Wir treffen uns zum Essen, Quatschen,
	und natürlich Spielen. Kommt vorbei!"""

[[events]]
date_time = 2024-05-07T18:30:00
title = "Spieleabend"
image = "spieleabend.webp"
image_alt = "Handkarten eines Spielers des Brettspiels „7 Wonders“"
summary = """
	Mit Brett, Karten, oder an der Leinwand. Wir treffen uns zum Essen, Quatschen,
	und natürlich Spielen. Kommt vorbei!"""

[[drinks]]
name = "Club Mate Original"
image = "club_mate.png"
size_litres = 0.5
price = 1.50

[[drinks]]
name = "Club Mate Beere"
image = "club_mate_beere.png"
size_litres = 0.5
price = 1.50

[[drinks]]
name = "Club Mate Zero"
image = "club_mate_zero.png"
size_litres = 0.5
price = 1.50

[[drinks]]
name = "Club Mate Granat"
image = "club_mate_granat.png"
size_litres = 0.5
price = 1.50

[[drinks]]
name = "Club Mate ICE-T"
image = "club_mate_icet.png"
size_litres = 0.5
price = 1.50

[[drinks]]
name = "Club Mate Winter"
image = "club_mate_winter.png"
size_litres = 0.5
price = 1.50

[[drinks]]
name = "Mio Mio Mate Original"
image = "mio_mio_mate.webp"
size_litres = 0.5
price = 1.50

[[drinks]]
name = "Mio Mio Cola"
image = "mio_mio_cola.webp"
size_litres = 0.5
price = 1.50

[[drinks]]
name = "Mio Mio Mate Ginger"
image = "mio_mio_mate_ginger.webp"
size_litres = 0.5
price = 1.50

[[drinks]]
name = "Mio Mio Mate Zero"
image = "mio_mio_mate_zero.webp"
size_litres = 0.5
price = 1.50

[[drinks]]
name = "Mate Mate"
image = "mate_mate.webp"
size_litres = 0.5
price = 1.50

[[drinks]]
name = "Kolle Mate"
image = "kolle_mate.webp"
size_litres = 0.5
price = 1.50

[[drinks]]
name = "Frau Kolle"
image = "frau_kolle.png"
size_litres = 0.5
price = 1.50

[[drinks]]
name = "Zotrine"
image = "zotrine.webp"
size_litres = 0.5
price = 1.50

[[drinks]]
name = "Kilimo"
image = "kilimo.jpg"
size_litres = 0.5
price = 1.50

[[drinks]]
name = "Kolla"
image = "kolla.webp"
size_litres = 0.5
price = 1.50

[[drinks]]
name = "Premium Cola"
image = "premium_cola.png"
size_litres = 0.5
price = 1.50

[[drinks]]
name = "Premium Cola Zero"
image = "premium_cola_zero.webp"
size_litres = 0.33
price = 1.50

[[drinks]]
name = "Spezi"
image = "spezi.webp"
size_litres = 0.5
price = 1.50

[[drinks]]
name = "Spezi Zero"
image = "spezi_zero.webp"
size_litres = 0.5
price = 1.50

[[drinks]]
name = "Fritz Spritz"
image = "fritz_spritz.webp"
size_litres = 0.5
price = 1.50

[[drinks]]
name = "Fritz Limo"
image = "fritz_limo.webp"
size_litres = 0.5
price = 1.50

[[drinks]]
name = "Fritz Kola Superzero"
image = "fritz_kola_superzero.webp"
size_litres = 0.5
price = 1.50

[[drinks]]
name = "Fritz Mischmasch"
image = "fritz_mischmasch.webp"
size_litres = 0.5
price = 1.50

[[drinks]]
name = "Wostok Blaubeere Salbei"
image = "wostok_blaubeere_salbei.webp"
size_litres = 0.33
price = 1.50

[[drinks]]
name = "Wostok Zitrone Minze"
image = "wostok_zitrone_minze.webp"
size_litres = 0.33
price = 1.50

[[drinks]]
name = "Wostok Birne Rosmarin"
image = "wostok_birne_rosmarin.webp"
size_litres = 0.33
price = 1.50

[[drinks]]
name = "Wostok Tannenwald"
image = "wostok_tannenwald.webp"
size_litres = 0.33
price = 1.50

[[drinks]]
name = "Bad Brambacher Grapefruit"
image = "bad_brambacher_grapefruit.png"
size_litres = 0.5
price = 1.00

[[drinks]]
name = "Bad Brambacher Orange"
image = "bad_brambacher_orange.png"
size_litres = 0.5
price = 1.00

[[drinks]]
name = "Bad Brambacher Johannisbeere"
image = "bad_brambacher_johannisbeere.png"
size_litres = 0.5
price = 1.00

[[drinks]]
name = "Bad Brambacher Zitrone"
image = "bad_brambacher_zitrone.png"
size_litres = 0.5
price = 1.00

[[drinks]]
name = "Heide Orangensaft"
image = "heide_orangensaft.png"
size_litres = 1.0
price = 1.00

[[drinks]]
name = "Heide Multivitaminsaft"
image = "heide_multivitamin.png"
size_litres = 1.0
price = 1.00

[[drinks]]
name = "Heide Apfelsaft"
image = "heide_apfelsaft.png"
size_litres = 1.0
price = 1.00

[[drinks]]
name = "Margon Still"
image = "margon_still.png"
size_litres = 0.75
price = 0.50

[[drinks]]
name = "Margon Medium"
image = "margon_medium.png"
size_litres = 0.75
price = 0.50

[[drinks]]
name = "Margon Classic"
image = "margon_classic.png"
size_litres = 0.75
price = 0.50
