baseURL = 'https://ascii-dresden.de'
languageCode = 'de-de'
title = 'Studierendencafé ascii'
theme = 'mediumsh'
[menu]

  [[menu.main]]
    identifier = "about"
    name = "Über uns"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Kontakt"
    url = "/contact/"
    weight = 10
  [[menu.main]]
    identifier = "products"
    name = "Sortiment"
    url = "/products/"
    weight = 10
  [[menu.main]]
    identifier = "association"
    name = "Verein"
    url = "/association/"
    weight = 10
  [[menu.main]]
    identifier = "impress"
    name = "Impressum"
    url = "/imprint"
    weight = 10
  [[menu.main]]
    identifier = "hours"
    name = "Öffnungszeiten"
    url = "/hours/"
    weight = 10

[params.social]
  github = "ascii-dresden"
  twitter = 'asciidresden'
  instagram = "asciidresden"
